### PR TITLE
currrent_time() default producing six hour offset here in US

### PR DESCRIPTION
**Pull request by MikeiLL**
I think this may solve the issue.

### CODE REVIEW

**Comment by Mte90** [comment]
You can override that value but as I can see:

* https://www.php.net/manual/en/function.time.php - actual timestamp by the server
* https://developer.wordpress.org/reference/functions/current_time/ - instead can use based on the parameter the one by mysql or the wordpress settings

**Comment by MikeiLL** [comment]
I was looking at this with a more adept (than me) friend, @Rosuav who suggested:

> It is a problem because the cron system expects Unix time. Using current_time('timestamp', true) would work, but that's the same as just time(), so defaulting to time() would be correct.

> The example is correct but the default is wrong, so it's only an issue if someone omits the time.

**Comment by Mte90** [comment]
Yes in this way make more sense, `current_time` without a parameter like it is as default is useless.
If you want to update the PR with that change I will it approve it :-D

**Comment by MikeiLL** [comment]
Isn't that what the current PR is? Default to `time()`? Perhaps we want to have the example override supply `current_time`. I could update.

**Comment by Mte90** [comment]
Yes if you can change the PR to `current_time` with the parameter so we can keep kind of compatibility.

**Pull request merged**
