### PR TITLE
Composer support

### PR DESCRIPTION
**Pull request by ghost**
I really like to use this class with composer, so I've added the support for it.

I've created a namespaced class `Mte90\CronPlus` which inherits all methods and properties from `CronPlus`.

Note: If you accept this pull request, remember to fix the file `/composer.json` (composer require an email address)

### CODE REVIEW

**Comment by Mte90** [comment]
I've to test that because in WordPress the minimum version of PHP is 5.2 and the namespace exist only on PHP 5.6.

**Comment by Mte90** [comment]
I've see that exist https://bitbucket.org/xrstf/composer-php52/src that generate an autoloader compatible with composer and is used by Yoast SEO.
The problem is that they use only the autoloader for php 5.2 and not also for the other version so you can't user namespace etc.
So I think that I can create a branch for composer and on for the master without.
What do you think about it?

PS: I've started a discussion on reddit https://www.reddit.com/r/Wordpress/comments/3vs6a1/composer_php_52_and_wordpress/

**Comment by Mte90** [comment]
The package now have a composer.json file.
Thank you for the inspiration :-)

**Comment by ghost** [comment]
Hi,
I don't know why I hadn't seen the notification, I'm sorry
However, thanks a lot!

**Pull request closed without merging**
